# Generated by Django 5.1.4 on 2025-01-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationaLevel',
            new_name='EducationLevel',
        ),
    ]
