# Generated by Django 5.1.4 on 2025-01-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_rename_educationalevel_educationlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='text',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='text',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='text',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
