# Generated by Django 5.1.4 on 2025-01-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_class_text_alter_educationlevel_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('classlevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.class')),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.classlevel'),
        ),
    ]
