# Generated by Django 5.1.4 on 2025-01-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_classlevel_alter_subject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='educationalevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.classlevel'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='classlevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.educationlevel'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.class'),
        ),
    ]
