# Generated by Django 5.1.4 on 2025-01-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_class_educationalevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('thumb', models.BinaryField()),
                ('uploaded_file', models.BinaryField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.resourcetype')),
            ],
            options={
                'verbose_name_plural': 'documents',
            },
        ),
    ]
