# Generated by Django 5.1.4 on 2025-01-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Grade',
        ),
    ]
