# Generated by Django 5.1.4 on 2025-01-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_rename_classlevel_classlevel_educationlevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='document',
            name='book_cover',
            field=models.FileField(default=1, upload_to='book_cover/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_pdf',
            field=models.FileField(default=2, upload_to='uploaded_pdf/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='caption',
            field=models.CharField(max_length=40),
        ),
    ]
