# Generated by Django 5.1.4 on 2025-01-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_remove_document_thumb_remove_document_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='book_cover',
        ),
        migrations.AddField(
            model_name='document',
            name='back_cover',
            field=models.FileField(default=1, upload_to='covers/back_cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='front_cover',
            field=models.FileField(default=2, upload_to='covers/front_cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='price',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
