# Generated by Django 5.1.4 on 2025-01-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_remove_document_book_cover_document_back_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_pdf',
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='back_cover',
            field=models.FileField(upload_to='covers/back_cover/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='front_cover',
            field=models.FileField(upload_to='covers/front_cover/'),
        ),
    ]
