# Generated by Django 5.1.4 on 2025-01-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_remove_document_uploaded_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='back_cover',
            field=models.FileField(upload_to='covers/back_covers/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='front_cover',
            field=models.FileField(upload_to='covers/front_covers/'),
        ),
    ]
