# Generated by Django 5.1.4 on 2025-01-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_alter_document_back_cover_alter_document_front_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='resourcetype',
            new_name='resource_type',
        ),
    ]
