# Generated by Django 5.1.4 on 2025-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_rename_resourcetype_document_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='back_cover',
            field=models.ImageField(upload_to='back_covers/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='front_cover',
            field=models.ImageField(upload_to='front_covers/'),
        ),
    ]
