databases:
  - name: education_resourcesdb
    plan: free
    databaseName: education_resources
    user: education_resources

services:
  - type: web
    plan: free
    name: education_resources
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn education_resources.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: education_resourcesdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4